Milestone: Support Responsive Web Design 💻📱🤩
ahmedeid6842/Portfolio pull request #4
Opened 2023-05-04 05:06 UTC by ahmedeid6842

- Added Media queries to Each section to achieve RWD
- Updated Header section if min-width > 768
  -  Added navigation list
  - change texts style to fix the new width 
- Updated Works section in case min-width > 768
  - Updated the width for each work card to fit the width
  - Each work card is split between  work image and work details
  - Align the work image on the card's right and the work details on the left then mirror it for the next card 
- Updated About section in case min-width>768
  -  Moved languages,... Drop down next to About myself 
- Updated Contact form section in case min-width > 768
  - Align the inputs field to the form center
- Updated a README documentation 
- Updated `index` and `style.css` files with some styling 

### Finally 😅😅

![jim-carrey-finally](https://user-images.githubusercontent.com/57197702/236115289-a937136b-51e5-4ba5-955a-2798e783c2cd.gif)

2023-05-04 17:56 UTC, zieeco requested changes
Hi @ahmedeid6842,

<img height="220" src="https://media3.giphy.com/media/bGCwmLDnwL25kCg3FV/giphy-downsized-medium.gif"/>

Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 17:56 UTC, zieeco commented on styles/main.css
> +  }
- Hey, let's try to improve our design by adjusting the styles on the image as it goes out of the card.

*Your card*
![Screenshot from 2023-05-04 18-44-12](https://user-images.githubusercontent.com/59397159/236287637-edb7616f-4b68-4050-aa1d-d3324ef64064.png)

*your design*
![image](https://user-images.githubusercontent.com/59397159/236287913-c9d16375-7e42-4c17-a2da-1fffcbc0e43b.png)

2023-05-04 17:56 UTC, zieeco commented on index.html
- Your styles are not reflecting on GitHub, kindly update the link to 
`<link rel="stylesheet" href="./styles/main.css">` to fix this issue.

2023-05-05 00:32 UTC, Efiamotu-1 requested changes
Hi @ahmedeid6842 >, 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- Good commit history :clap: 
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 00:32 UTC, Efiamotu-1 commented on index.html
> -                <span>JavaScript</span>
- [ ] your desktop design for the technologies section in your about me is largely inconsistent with the figma template as shown below please kindly work on it as it is very important to always achieve the given figma design to the latter :+1: 
- figma design
![in-f](https://user-images.githubusercontent.com/89055502/236356411-686ceb7d-2cd2-4a31-9d97-6978d582794c.png)
- your design
![in-s](https://user-images.githubusercontent.com/89055502/236356422-ac395376-1002-453b-bc91-7b0939b65a93.png)

2023-05-05 00:32 UTC, Efiamotu-1 commented on index.html
> -                <img src="./images/JavaScript.svg" alt="">
- [ ] your mobile design for the technologies section is not consistent with the provided figma template please make sure to fix this as well :+1: 
- figma design 
![in-mf](https://user-images.githubusercontent.com/89055502/236356603-5e5acf37-33a5-4206-a208-a52985e8920b.png)
- your design
![in-m](https://user-images.githubusercontent.com/89055502/236356611-f5280062-71c1-472a-b827-e84c9082c546.png)

2023-05-05 00:32 UTC, Efiamotu-1 commented on index.html
> -    <section class="work">
- [ ] There is little spacing between the header and the works section in your desing however this is not the same as in the case in the figma template please try to design your web page to match the design of the figma template :+1: 
- figma design
![fig-d](https://user-images.githubusercontent.com/89055502/236356808-94a23c99-7339-47f0-805e-8fc545409d03.png)
- your design
![fig-s](https://user-images.githubusercontent.com/89055502/236356817-ce4be0d0-d480-473e-9d73-020813b362ef.png)

2023-05-05 06:53 UTC, Efiamotu-1 approved these changes
Hi @ahmedeid6842 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good commit history :100: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 06:53 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- I will suggest that you use this particular css stlying for the margin `margin: 2.5rem 0;` in your line `97` of `main.css` to achieve the design shown below becasue currently there is margin to the left and right of your header :+1:  :grin: 
![ach](https://user-images.githubusercontent.com/89055502/236393762-aee5d04d-97f3-4694-8a0f-7cae08ed6117.png)

2023-05-05 07:05 UTC, ahmedeid6842 commented
![7fb4d55fa09fc4f5426e6d5934d1d02f](https://user-images.githubusercontent.com/57197702/236395820-a300cb53-2cec-4d36-922d-b42a3288501f.gif)

2023-05-05 07:06 UTC, merged

2023-05-05 08:33 UTC, bellom commented
Hello @ahmedeid6842 👋,

_This is an additional review as a result of the second opinion request._

Sorry for the late response, this is due to the hour you asked for the SO.

I'm happy 🙂  to see your project has been approved, and thanks for bringing this to us we will reach out to the CR.

Thank you.

Keep rocking 🚀!